project:
  type: book

book:
  title: "livro"
  author: "Norah Jones"
  date: "11/11/2024"
  chapters:
    - index.qmd
    - capitulos/intro.qmd
    - capitulos/summary.qmd
    - capitulos/references.qmd

bibliography: references.bib

format:
  html:
    theme: superhero
  pdf:
    documentclass: scrreprt



